#### Installing library numpy with pip

support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.



In [10]:
!pip install numpy

In [1]:
import numpy as np

a = np.array([1, 2, 3])

a

array([1, 2, 3])

In [4]:
b = np.array([(1, 5, 3),(7, 8, 10), (5, 4, 2)])

print(b)

[[ 1  5  3]
 [ 7  8 10]
 [ 5  4  2]]


In [6]:
matrizZero = np.zeros((4, 3))

matrizZero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
b = np.ones((4, 3))

b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
c = np.eye(4)

c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
b.sum()

12.0

In [19]:
b.mean()

1.0

In [20]:
b.std()

0.0