In [1]:
import pandas as pd

alunos = {'Nome': ['Ricardo', 'Pedro', 'Roberto'],
          'Nota': [4, 7, 8],
          'Aprovado':['Não', 'Sim', 'Sim']}

In [3]:
dataframe = pd.DataFrame(alunos)

dataframe

Nome  Nota Aprovado
0  Ricardo     4      Não
1    Pedro     7      Sim
2  Roberto     8      Sim

### Series

You can think series as a single column of a  dataframe (one-dimensional)

In [9]:
object1 = pd.Series([2, 6, 8, 7, 10])

print(object1)

0     2
1     6
2     8
3     7
4    10
dtype: int64


In [13]:
import numpy as np

array1 = np.array([2, 6, 8, 7, 10])
array2 = np.array([(2, 6, 8, 7, 10), (2, 9, 5, 7, 1)])

print(array1, "\n")

print(array2)

[ 2  6  8  7 10] 

[[ 2  6  8  7 10]
 [ 2  9  5  7  1]]


series must be 1-dimensional

In [14]:
object2 = pd.Series(array1)

print(array1)

[ 2  6  8  7 10]


In [15]:
object2 = pd.Series(array2)

print(array2)

Exception: Data must be 1-dimensional